export const TEST_CASES = [
  {
    label: "Manual Provisioning via CLI",
    status: "ongoing",
    required: true,
    subtests: [
      {
        label: "OMCI Activation (Automated)",
        type: "checklist",
        status: "complete",
        required: true,
      },
      {
        label: "CLI Config (Automated)",
        type: "checklist",
        status: "pending",
        required: false,
      },
      {
        label: "NMS WAN (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "ONU WAN Status (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: false,
      },
      {
        label: "ONU WAN Config (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: false,
      },
      {
        label: "Speedtest Wired (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wireless (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
    ],
  },
  {
    label: "Activation via UMP",
    status: "ongoing",
    required: true,
    subtests: [
      {
        label: "Speedtest Wired (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wireless (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: false,
      },
    ],
  },
  {
    label: "Change Package via UMP",
    status: "ongoing",
    subtests: [
      {
        label: "ONU WAN Status (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "ONU WAN Config (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: false,
      },
      {
        label: "Speedtest Wired (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wireless (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
    ],
  },
  {
    label: "Suspend and Resume via UMP",
    status: "ongoing",
    required: true,
    subtests: [
      {
        label: "OMCI Activation (Automated)",
        type: "checklist",
        status: "pending",
        required: true,
      },
      {
        label: "CLI Config (Automated)",
        type: "checklist",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wireless (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
    ],
  },
  {
    label: "Reboot ONT and Clear BRAS",
    status: "ongoing",
    required: true,
    subtests: [
      {
        label: "OMCI Activation (Automated)",
        type: "checklist",
        status: "pending",
        required: true,
      },
      {
        label: "CLI Config (Automated)",
        type: "checklist",
        status: "pending",
        required: false,
      },
      {
        label: "ONU WAN Status (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "ONU WAN Config (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wired (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: false,
      },
      {
        label: "Speedtest Wireless (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
    ],
  },
  {
    label: "Factory Reset ONU",
    status: "ongoing",
    required: false,
    subtests: [
      {
        label: "OMCI Activation (Automated)",
        type: "checklist",
        status: "pending",
        required: true,
      },
      {
        label: "CLI Config (Automated)",
        type: "checklist",
        status: "pending",
        required: true,
      },
      {
        label: "NMS WAN (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wireless (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
    ],
  },
  {
    label: "Terminate via UMP",
    status: "ongoing",
    required: true,
    subtests: [
      {
        label: "OMCI Activation (Automated)",
        type: "checklist",
        status: "pending",
        required: false,
      },
      {
        label: "CLI Config (Automated)",
        type: "checklist",
        status: "pending",
        required: false,
      },
      {
        label: "NMS WAN (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "ONU WAN Config (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wired (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: false,
      },
      {
        label: "Speedtest Wireless (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
    ],
  },
  {
    label: "IPv6 Test",
    status: "ongoing",
    required: false,
    subtests: [
      {
        label: "ONU WAN Status (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: false,
      },
      {
        label: "ONU WAN Config (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wired (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wireless (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
    ],
  },
  {
    label: "Customer Care View",
    status: "ongoing",
    required: true,
    subtests: [
      {
        label: "OMCI Activation (Automated)",
        type: "checklist",
        status: "pending",
        required: true,
      },
      {
        label: "CLI Config (Automated)",
        type: "checklist",
        status: "pending",
        required: true,
      },
      {
        label: "NMS WAN (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wired (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wireless (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
    ],
  },
  {
    label: "Activation via JOMOBILE",
    status: "ongoing",
    required: true,
    subtests: [
      {
        label: "OMCI Activation (Automated)",
        type: "checklist",
        status: "pending",
        required: true,
      },
      {
        label: "CLI Config (Automated)",
        type: "checklist",
        status: "pending",
        required: true,
      },
      {
        label: "NMS WAN (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "ONU WAN Status (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "ONU WAN Config (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
      {
        label: "Speedtest Wired (Upload Screenshot)",
        type: "upload",
        status: "pending",
        required: true,
      },
    ],
  },
];
